name:                Neural
version:             0.1.0.0
github:              "vivekmyers/Neural"
license:             BSD3
author:              "Vivek Myers" 
maintainer:          "vivek.myers@gmail.com"
copyright:           "Vivek Myers"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/vivekmyers>

dependencies:
- base >= 4.7 && < 5
- random
- transformers
- bytestring

library:
  source-dirs: src

executables:
  neural:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - Neural

tests:
  Neural-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Neural
